name: Deploy to Server

on:
  push:
    branches: [ main ]  # Change "main" to your production branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest  # Replace with a specific runner if needed
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.1  # Or another SSH deployment action
        with:
          host: ${{ secrets.SERVER_IP_OR_HOSTNAME }}  # Replace with your server details
          username: ${{ secrets.SERVER_USERNAME }}  # Replace with your server username
          key: ${{ secrets.DEPLOY_KEY }}  # Use the secret if you created one
          port: 22  # Replace with your server's SSH port if different
          script: |  # Deployment commands for your project
            cd public_html  # Replace with the target directory
            rm -rf dist/*  # Remove existing files (optional, be cautious)
            cp -r ./dist/* .  # Copy the dist folder contents to the server
            # Add any additional deployment commands (e.g., npm install, server restart)

